site_name: WL Language Specification
site_author: Robert Jacobson
site_description: Wolfram Language Specification
repo_url: https://github.com/WLTools/LanguageSpec

# nav is handled by MkDocs Awesome Pages Plugin
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin

theme:
#    name: flatly
#    include_sidebar: true
    name: null
    custom_dir: 'custom_theme'
    highlightjs: false
    latex: true
#    name: bootstrap
#    custom_dir: theme_overides

extra_css:
  - extras/mma.css

# extra_javascript: ['extras/fixnav.js']
#extra_css: ['extras/fixnav.css']

nav:
    - 'Language Specification':
        - "Index" : 'Specification/index.md'
        - 'Syntax':
            - 'Index': 'Specification/Syntax/index.md'
            - 'Number Representations': 'Specification/Syntax/Number-representations.md'
            - 'Operator Table': 'Specification/Syntax/OperatorTable.md'
            - 'Pseudo Operators': 'Specification/Syntax/Pseudo-operators.md'
        - 'Semantics':
            - 'Index': 'Specification/Semantics/index.md'
            - 'Number Literals': 'Specification/Semantics/Number-literal-semantics.md'
        - 'Interfaces':
            - 'Index' : 'Specification/Interfaces/index.md'
        - 'Standard Library':
            - 'Index': 'Specification/StandardLibrary/index.md'


extra:
    'topnav':
        - 'Language Specification': 'Specification/index.md'
        - 'Resources':
            - "ToDo's": 'Resources/index.md'
            - 'Exploring Mathematica': 'Resources/Exploring-Mathematica.md'
            - 'List of WL Projects': 'Resources/List-of-W-Language-Projects.md'
            - 'Homeless Content': 'Resources/Homeless-content.md'
        - 'Contributing': 'Contributing/index.md'
#            - 'How to Contribute': 'Contributing/index.md'
#            - 'Style Guide': 'Contributing/Style-Guide.md'

markdown_extensions:
    - toc:
        permalink: True
    - sane_lists
    - wikilinks
    - admonition
    - footnotes
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        use_pygments: true
        css_class: 'language-mma'
        guess_lang: false
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

plugins:
    - search
