site_name: Wolfram Language Specification
site_author: Robert Jacobson
site_description: Wolfram Language Specification
repo_url: https://github.com/WLTools/LanguageSpec

# nav is handled by MkDocs Awesome Pages Plugin
# https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin

theme:
    name: readthedocs
    include_homepage_in_sidebar: false
    prev_next_buttons_location: 'both'
    navigation_depth: 4
    sticky_navigation: true
    titles_only: false
    collapse_navigation: false
    highlightjs: false

extra_css:
    - extras/material-icons.css
    - extras/admonitions.css
    - extras/mma.css
    - extras/fixes.css
    - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css'
extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js'
    - extras/usekratex.js

nav:
    - 'Language Specification':
        - 'Index': 'Specification/index.md'
        - 'Syntax':
            - 'Index': 'Specification/Syntax/index.md'
            - 'Number Representations': 'Specification/Syntax/Number-representations.md'
            - 'Operator Table': 'Specification/Syntax/OperatorTable.md'
            - 'Pseudo Operators': 'Specification/Syntax/Pseudo-operators.md'
        - 'Semantics':
            - 'Index': 'Specification/Semantics/index.md'
            - 'Number Literals': 'Specification/Semantics/Number-literal-semantics.md'
        - 'Interfaces':
            - 'Index': 'Specification/Interfaces/index.md'
        - 'Standard Library':
            - 'Index': 'Specification/StandardLibrary/index.md'
    - 'Resources':
        - 'Index': 'Resources/index.md'
        - 'Exploring Mathematica': 'Resources/Exploring-Mathematica.md'
        - 'List of WL Projects': 'Resources/List-of-W-Language-Projects.md'
        - 'Homeless Content': 'Resources/Homeless-content.md'
    - 'Contributing':
       - 'How to Contribute': 'Contributing/index.md'
       - 'Style Guide': 'Contributing/Style-Guide.md'

markdown_extensions:
    - toc:
        permalink: True
    - sane_lists
    - admonition
    - footnotes
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.highlight:
        use_pygments: true
        guess_lang: false
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

plugins:
    - search
